### ISSUE TITLE
DB.JSON NOT FOUND

### ISSUE THREAD

**Issue by Siemator** [Dalciop/sniper#1]
just do it
![image](https://user-images.githubusercontent.com/13433324/179416996-598e47d7-4eeb-41cd-beee-88fba45b5718.png)

**Comment by Dalciop** [comment]
Sniper now throw exception when db.json is not found and create basic template of it.

![obraz](https://user-images.githubusercontent.com/65959767/179417592-ca21e2b6-089f-4f5a-8ee4-14a96a1b4b5f.png)
