### ISSUE TITLE
:Biblethump:

### ISSUE THREAD

**Issue by Siemator** [Dalciop/sniper#2]
![image](https://user-images.githubusercontent.com/13433324/179418460-943342f3-7c29-4341-a059-5b0cc9f45dce.png)

**Comment by Dalciop** [comment]
Sniper returns error when application values are incorrect

![obraz](https://user-images.githubusercontent.com/65959767/179419107-62bbbb31-d74b-4b56-b86c-a5af2dc67670.png)

**Comment by Siemator** [comment]
are you sure about that ?

**Comment by Dalciop** [comment]
now should work 

`def get_NoOAuth():
        try:    
            response = post(TOKEN_URL, data=RequestData.NoOAuthData)
            response = response.json().get('access_token')
        except:
            raise Exception('Wrong application values! Please make sure that client_id and client_secret are correct!')
        return response

    def get_OAuth(code):
        try: 
            response = post(TOKEN_URL, data=RequestData.OAuthData(code))
            response = response.json()
        except:
            raise Exception('Wrong application values! Please make sure that client_id and client_secret are correct!')
        return response `
